sonar.projectKey=pigtown-barbershop
sonar.projectName=PigTown Barbershop
sonar.sources=app,components,lib,hooks,drizzle
sonar.tests=__tests__
sonar.exclusions=**/node_modules/**,**/.next/**,**/components/ui/**,**/*.d.ts,**/scratch/**,**/my-attendance-app/**
sonar.javascript.lcov.reportPaths=metrics/coverage/lcov.info
sonar.sourceEncoding=UTF-8
