/**
 * ========================================
 * PIGTOWN BARBERSHOP - DATABASE LAYER
 * ========================================
 * 
 * Using Supabase Client for all database operations
 * (Drizzle ORM is available for server-side operations in lib/db-drizzle.ts)
 */

import { createClient } from "@supabase/supabase-js"

// =============================
// Supabase Client Configuration
// =============================
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://leoriloxnohuwzyapcou.supabase.co"
const supabaseAnonKey =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxlb3JpbG94bm9odXd6eWFwY291Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxNjcyOTUsImV4cCI6MjA5Mzc0MzI5NX0.g0FEx9DeD-Lfi6ZFZcFu14iswzhAGKa0Z9SHuk03S34"

if (!supabaseUrl) {
  throw new Error("Missing NEXT_PUBLIC_SUPABASE_URL")
}
if (!supabaseAnonKey) {
  throw new Error("Missing NEXT_PUBLIC_SUPABASE_ANON_KEY")
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
})

// =============================
// TypeScript Interfaces
// =============================

export interface User {
  id: string
  email?: string
  name: string
  position?: string
  branch_id?: string
  phone?: string
  address?: string
  status?: string
  role?: string
  pin?: string
  salary?: number
  commission_rate?: number
  created_at: string
}

export interface Branch {
  id: string
  name: string
  address?: string
  phone?: string
  status?: string
  manager_id?: string
  created_at: string
}

export interface Service {
  id: string
  name: string
  description?: string
  price: number
  duration?: number
  category_id?: string
  type?: string
  stock?: number
  aktif?: boolean
  commission_rate?: number
  created_at: string
}

export interface ServiceCategory {
  id: string
  name: string
  description?: string
  is_active: boolean
  created_at: string
}

export interface ServiceWithCategory extends Service {
  category?: ServiceCategory
  service_categories?: ServiceCategory
}

export interface Transaction {
  id: string
  transaction_number: string
  receipt_number?: string
  cashier_id?: number
  server_id?: number
  branch_id?: string
  cashier_name?: string
  server_name?: string
  branch_name?: string
  customer_name?: string
  subtotal: number
  discount_amount: number
  total_amount: number
  payment_method: string
  payment_status?: string
  notes?: string
  created_at: string
  // Extended properties for UI
  cashier?: { name: string }
  server?: { name: string }
  branch?: { name: string }
  transaction_items?: TransactionItem[]
}

export interface TransactionItem {
  id: string
  transaction_id: string
  service_id: string
  service_name?: string
  service_type?: string
  service_category?: string
  quantity: number
  unit_price: number
  total_price: number
  commission_status?: string
  commission_type?: 'percentage' | 'fixed'
  commission_value?: number
  commission_amount?: number
  barber_id?: number
  created_at: string
  // Extended properties for UI
  service?: {
    name: string
    price: number
  }
  has_commission?: boolean
}

export interface Attendance {
  id: string
  user_id: number // Changed from string to number (INTEGER in database)
  branch_id?: string
  shift_type?: string
  check_in_time?: string
  check_out_time?: string
  break_start_time?: string
  break_end_time?: string
  total_hours?: number
  break_duration?: number
  status?: string
  check_in_photo?: string
  check_out_photo?: string
  date: string
  created_at: string
}

export interface Point {
  id: string
  user_id: string
  points_earned: number
  points_type?: string
  description?: string
  created_at: string
}

export interface Kasbon {
  id: string
  user_id: string
  amount: number
  reason?: string
  status?: string
  request_date?: string
  due_date?: string
  notes?: string
  approved_by?: string
  approved_at?: string
  created_at: string
}

export interface KasbonWithUser extends Kasbon {
  user?: User
}

export interface Expense {
  id: string
  branch_id?: string
  category?: string
  description?: string
  amount: number
  status?: string
  request_date?: string
  due_date?: string
  receipt_url?: string
  notes?: string
  requested_by?: string
  approved_by?: string
  approved_at?: string
  created_at: string
}

export interface ReceiptTemplate {
  id: string
  name: string
  header_text?: string
  footer_text?: string
  logo_url?: string
  is_active?: boolean
  is_default?: boolean
  branch_id?: string
  created_at?: string
}

// =============================
// TRANSACTION FUNCTIONS
// =============================

export async function createTransaction(data: {
  transaction_number?: string // Make optional, will be generated by database
  receipt_number?: string
  cashier_id?: number
  server_id?: number
  branch_id?: string
  cashier_name?: string
  server_name?: string
  branch_name?: string
  customer_name?: string
  subtotal: number
  discount_amount: number
  total_amount: number
  payment_method: string
  payment_status?: string
  notes?: string
}) {
  try {
    // Generate transaction number from database function if not provided
    let transactionNumber: string = data.transaction_number || ''
    
    if (!transactionNumber) {
      const { data: result, error: seqError } = await supabase
        .rpc('get_next_transaction_number')
      
      if (seqError || !result) {
        console.error('[createTransaction] Error getting transaction number:', seqError)
        // Fallback to timestamp-based number with Indonesian format if function fails
        const now = new Date()
        const dd = String(now.getDate()).padStart(2, '0')
        const mm = String(now.getMonth() + 1).padStart(2, '0')
        const yyyy = now.getFullYear()
        const timestamp = Date.now().toString().slice(-4)
        transactionNumber = `TRX-${dd}${mm}${yyyy}-${timestamp}`
      } else {
        transactionNumber = result as string
      }
    }
    
    // Generate receipt number if not provided (same format as transaction number)
    const receiptNumber = data.receipt_number || transactionNumber.replace('TRX-', 'RCP-')
    
    const { data: transaction, error } = await supabase
      .from('transactions')
      .insert({
        ...data,
        transaction_number: transactionNumber,
        receipt_number: receiptNumber,
        payment_status: data.payment_status || 'completed',
      })
      .select()
      .single()
    
    if (error) throw error
    return { data: transaction, error: null }
  } catch (error: any) {
    console.error('[createTransaction] Error:', error)
    return { data: null, error }
  }
}

export async function getTransactions(branchId?: string, limit = 50) {
  try {
    let query = supabase
      .from('transactions')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(limit)
    
    if (branchId && branchId !== 'all') {
      query = query.eq('branch_id', branchId)
    }
    
    const { data, error } = await query
    if (error) throw error
    return { data: data || [], error: null }
  } catch (error: any) {
    console.error('[getTransactions] Error:', error)
    return { data: [], error }
  }
}

export async function getTransactionById(id: string) {
  try {
    const { data, error } = await supabase
      .from('transactions')
      .select('*')
      .eq('id', id)
      .single()
    
    if (error) throw error
    return { data, error: null }
  } catch (error: any) {
    console.error('[getTransactionById] Error:', error)
    return { data: null, error }
  }
}

export async function createTransactionItems(items: Array<{
  transaction_id: string
  service_id: number // Changed from string to number (INTEGER in database)
  quantity: number
  unit_price: number
  total_price: number
  commission_status?: string
  commission_type?: string
  commission_value?: number
  commission_amount?: number
  barber_id?: number // Changed from string to number (INTEGER in database)
}>) {
  try {
    console.log('[createTransactionItems] Attempting to insert items:', JSON.stringify(items, null, 2))
    
    const { data, error } = await supabase
      .from('transaction_items')
      .insert(items)
      .select()
    
    if (error) {
      console.error('[createTransactionItems] Supabase error details:', {
        message: error.message,
        details: error.details,
        hint: error.hint,
        code: error.code
      })
      throw error
    }
    
    console.log('[createTransactionItems] Success! Inserted items:', data)
    return { data: data || [], error: null }
  } catch (error: any) {
    console.error('[createTransactionItems] Caught error:', {
      message: error?.message,
      name: error?.name,
      stack: error?.stack,
      full: error
    })
    return { data: [], error }
  }
}

// =============================
// SERVICES FUNCTIONS
// =============================

export async function getServices() {
  try {
    const { data, error } = await supabase
      .from('services')
      .select('*')
      .eq('aktif', true)
      .order('name')
    
    if (error) throw error
    return { data: data || [], error: null }
  } catch (error: any) {
    console.error('[getServices] Error:', error)
    return { data: [], error }
  }
}

export async function getServicesWithCategories() {
  try {
    const { data, error } = await supabase
      .from('services')
      .select('*, service_categories(*)')
      .eq('aktif', true)
      .order('name')
    
    if (error) throw error
    return { data: data || [], error: null }
  } catch (error: any) {
    console.error('[getServicesWithCategories] Error:', error)
    return { data: [], error }
  }
}

export async function getServiceCategories() {
  try {
    const { data, error } = await supabase
      .from('service_categories')
      .select('*')
      .eq('is_active', true)
      .order('name')
    
    if (error) throw error
    return { data: data || [], error: null }
  } catch (error: any) {
    console.error('[getServiceCategories] Error:', error)
    return { data: [], error }
  }
}

// =============================
// USERS FUNCTIONS
// =============================

export async function getUsers(branchId?: string) {
  try {
    let query = supabase
      .from('users')
      .select('*')
      .order('name')
    
    if (branchId && branchId !== 'all') {
      query = query.eq('branch_id', branchId)
    }
    
    const { data, error } = await query
    if (error) throw error
    return { data: data || [], error: null }
  } catch (error: any) {
    console.error('[getUsers] Error:', error)
    return { data: [], error }
  }
}

export async function getUserByEmail(email: string) {
  try {
    const { data, error } = await supabase
      .from('users')
      .select('*, password')
      .eq('email', email)
      .single()
    
    if (error) throw error
    return { data, error: null }
  } catch (error: any) {
    console.error('[getUserByEmail] Error:', error)
    return { data: null, error }
  }
}

export async function getCurrentUser() {
  // This is a placeholder - implement based on your auth system
  if (typeof window === 'undefined') return { data: null, error: null }
  
  const userStr = localStorage.getItem('user')
  if (!userStr) return { data: null, error: null }
  
  try {
    const user = JSON.parse(userStr)
    return { data: user, error: null }
  } catch (error) {
    return { data: null, error }
  }
}

export async function updateUserPin(userId: string, pin: string) {
  try {
    const { data, error } = await supabase
      .from('users')
      .update({ pin })
      .eq('id', userId)
      .select()
      .single()
    
    if (error) throw error
    return { data, error: null }
  } catch (error: any) {
    console.error('[updateUserPin] Error:', error)
    return { data: null, error }
  }
}

// =============================
// BRANCHES FUNCTIONS
// =============================

export async function getBranches() {
  try {
    const { data, error } = await supabase
      .from('branches')
      .select('*')
      .eq('status', 'active')
      .order('name')
    
    if (error) throw error
    return { data: data || [], error: null }
  } catch (error: any) {
    console.error('[getBranches] Error:', error)
    return { data: [], error }
  }
}

// =============================
// ATTENDANCE FUNCTIONS
// =============================

export async function getAttendance(branchId?: string, startDate?: string, endDate?: string) {
  try {
    console.log('[getAttendance] Parameters:', { branchId, startDate, endDate })
    
    let query = supabase
      .from('attendance')
      .select(`
        *,
        branches:branch_id (
          id,
          name,
          shifts
        ),
        users:user_id (
          id,
          name,
          position
        )
      `)
      .order('date', { ascending: false })
      .order('created_at', { ascending: false })
    
    if (branchId && branchId !== 'all') {
      query = query.eq('branch_id', branchId)
    }
    
    if (startDate) {
      query = query.gte('date', startDate)
    }
    
    if (endDate) {
      query = query.lte('date', endDate)
    }
    
    console.log('[getAttendance] Executing query...')
    const { data, error } = await query
    
    if (error) {
      console.error('[getAttendance] Supabase error:', {
        message: error.message,
        details: error.details,
        hint: error.hint,
        code: error.code,
        fullError: JSON.stringify(error)
      })
      throw error
    }
    
    console.log('[getAttendance] Success! Rows returned:', data?.length || 0)
    return { data: data || [], error: null }
  } catch (error: any) {
    console.error('[getAttendance] Caught error:', {
      message: error?.message,
      name: error?.name,
      code: error?.code,
      details: error?.details,
      hint: error?.hint,
      stack: error?.stack,
      fullError: JSON.stringify(error, Object.getOwnPropertyNames(error))
    })
    return { data: [], error }
  }
}

// =============================
// POINTS FUNCTIONS
// =============================

export async function getPoints(userId?: string) {
  try {
    let query = supabase
      .from('points')
      .select('*')
      .order('created_at', { ascending: false })
    
    // Only filter by user_id if userId is provided AND not "all"
    if (userId && userId !== 'all') {
      query = query.eq('user_id', parseInt(userId))
    }
    
    const { data, error } = await query
    if (error) throw error
    return { data: data || [], error: null }
  } catch (error: any) {
    console.error('[getPoints] Error:', error)
    return { data: [], error }
  }
}

export async function addPoint(data: {
  user_id: string
  points_earned: number
  points_type: string
  description: string
}) {
  try {
    const { data: point, error } = await supabase
      .from('points')
      .insert(data)
      .select()
      .single()
    
    if (error) throw error
    return { data: point, error: null }
  } catch (error: any) {
    console.error('[addPoint] Error:', error)
    return { data: null, error }
  }
}

// =============================
// KASBON FUNCTIONS
// =============================

export async function getKasbon(branchId?: string, statusFilter?: string) {
  try {
    // Get all kasbon
    const { data: kasbonData, error: kasbonError } = await supabase
      .from('kasbon')
      .select('*')
      .order('created_at', { ascending: false })
    
    if (kasbonError) throw kasbonError
    
    // Get all users
    const { data: users } = await supabase
      .from('users')
      .select('id, name, email, branch_id')
    
    // Create user map for quick lookup
    const userMap = new Map(users?.map(u => [u.id, u]) || [])
    
    // Combine kasbon with user data
    let kasbonWithUsers = (kasbonData || []).map(kasbon => ({
      ...kasbon,
      user: userMap.get(kasbon.user_id) || null
    }))
    
    // Filter by status if specified
    if (statusFilter && statusFilter !== 'all') {
      kasbonWithUsers = kasbonWithUsers.filter(k => k.status === statusFilter)
    }
    
    // Filter by branch if specified
    if (branchId && branchId !== 'all') {
      kasbonWithUsers = kasbonWithUsers.filter(k => k.user?.branch_id === branchId)
    }
    
    return { data: kasbonWithUsers, error: null }
  } catch (error: any) {
    console.error('[getKasbon] Error:', error)
    return { data: [], error }
  }
}

// =============================
// EXPENSES FUNCTIONS
// =============================

export async function getExpenses(branchId?: string, statusFilter?: string) {
  try {
    let query = supabase
      .from('expenses')
      .select('*')
      .order('created_at', { ascending: false })
    
    if (branchId && branchId !== 'all') {
      query = query.eq('branch_id', branchId)
    }
    
    if (statusFilter && statusFilter !== 'all') {
      query = query.eq('status', statusFilter)
    }
    
    const { data, error } = await query
    if (error) throw error
    return { data: data || [], error: null }
  } catch (error: any) {
    console.error('[getExpenses] Error:', error)
    return { data: [], error }
  }
}

// =============================
// STATISTICS FUNCTIONS
// =============================

export async function getTransactionStats(branchId?: string, startDate?: string, endDate?: string) {
  try {
    let query = supabase
      .from('transactions')
      .select('total_amount')
    
    if (branchId && branchId !== 'all') {
      query = query.eq('branch_id', branchId)
    }
    
    if (startDate) {
      query = query.gte('created_at', startDate)
    }
    
    if (endDate) {
      query = query.lte('created_at', endDate)
    }
    
    const { data, error } = await query
    if (error) throw error
    
    const total_revenue = data?.reduce((sum, t) => sum + Number(t.total_amount), 0) || 0
    const total_transactions = data?.length || 0
    const avg_transaction = total_transactions > 0 ? total_revenue / total_transactions : 0
    
    return {
      data: {
        total_revenue,
        total_transactions,
        avg_transaction,
      },
      error: null
    }
  } catch (error: any) {
    console.error('[getTransactionStats] Error:', error)
    return { data: null, error }
  }
}

// =============================
// RECEIPT TEMPLATE FUNCTIONS
// =============================

export async function getReceiptTemplate(branchId?: string) {
  try {
    let query = supabase
      .from('receipt_templates')
      .select('*')
      .eq('is_active', true)
      .limit(1)
    
    if (branchId) {
      query = query.eq('branch_id', branchId)
    }
    
    const { data, error } = await query.maybeSingle() // Use maybeSingle() to handle no rows
    
    // If no template found, return default template
    if (!data && !error) {
      return {
        data: {
          id: 'default',
          name: 'Default Template',
          header_text: 'PIGTOWN BARBERSHOP\nJl. Contoh No. 123\nTelp: (021) 1234-5678',
          footer_text: 'Terima kasih atas kunjungan Anda!\nSampai jumpa kembali!',
          logo_url: '/images/pigtown-logo.png',
          is_active: true,
          is_default: true,
          branch_id: branchId || null,
          created_at: new Date().toISOString(),
        },
        error: null
      }
    }
    
    return { data: data || null, error: error || null }
  } catch (error: any) {
    console.error('[getReceiptTemplate] Error:', error)
    // Return default template on error
    return {
      data: {
        id: 'default',
        name: 'Default Template',
        header_text: 'PIGTOWN BARBERSHOP\nJl. Contoh No. 123\nTelp: (021) 1234-5678',
        footer_text: 'Terima kasih atas kunjungan Anda!\nSampai jumpa kembali!',
        logo_url: '/images/pigtown-logo.png',
        is_active: true,
        is_default: true,
        branch_id: branchId || null,
        created_at: new Date().toISOString(),
      },
      error: null
    }
  }
}

export async function getActiveReceiptTemplate() {
  try {
    const { data, error } = await supabase
      .from('receipt_templates')
      .select('*')
      .eq('is_default', true)
      .limit(1)
      .maybeSingle() // Use maybeSingle() instead of single() to handle no rows
    
    // If no template found, return default template
    if (!data && !error) {
      return {
        data: {
          id: 'default',
          name: 'Default Template',
          header_text: 'PIGTOWN BARBERSHOP\nJl. Contoh No. 123\nTelp: (021) 1234-5678',
          footer_text: 'Terima kasih atas kunjungan Anda!\nSampai jumpa kembali!',
          logo_url: '/images/pigtown-logo.png',
          is_active: true,
          is_default: true,
          branch_id: null,
          created_at: new Date().toISOString(),
        },
        error: null
      }
    }
    
    return { data: data || null, error: error || null }
  } catch (error: any) {
    console.error('[getActiveReceiptTemplate] Error:', error)
    // Return default template on error
    return {
      data: {
        id: 'default',
        name: 'Default Template',
        header_text: 'PIGTOWN BARBERSHOP\nJl. Contoh No. 123\nTelp: (021) 1234-5678',
        footer_text: 'Terima kasih atas kunjungan Anda!\nSampai jumpa kembali!',
        logo_url: '/images/pigtown-logo.png',
        is_active: true,
        is_default: true,
        branch_id: null,
        created_at: new Date().toISOString(),
      },
      error: null
    }
  }
}

// =============================
// STUB FUNCTIONS (To be implemented)
// =============================

// These are placeholder functions to prevent build errors
// Implement them as needed

export async function getEmployees(branchId?: string) {
  return getUsers(branchId)
}

export async function getOutletStock() {
  try {
    const { data, error } = await supabase
      .from('services')
      .select('*')
      .eq('type', 'product')
      .order('name')
    if (error) throw error
    return { data: data || [], error: null }
  } catch (error: any) {
    return { data: [], error }
  }
}

export async function getLowStockAlerts() {
  try {
    const { data, error } = await supabase
      .from('services')
      .select('*')
      .eq('type', 'product')
      .lt('stock', 10)
      .order('stock', { ascending: true })
    if (error) throw error
    return { data: data || [], error: null }
  } catch (error: any) {
    return { data: [], error }
  }
}

export async function updateOutletStock(id: string, stock: number) {
  try {
    const { data, error } = await supabase
      .from('services')
      .update({ stock })
      .eq('id', id)
      .select()
      .single()
    if (error) throw error
    return { data, error: null }
  } catch (error: any) {
    return { data: null, error }
  }
}

export async function getEmployeeAbsenceInfo(userId: string) {
  try {
    const { data, error } = await supabase
      .from('users')
      .select('max_absent_days, current_absent_days')
      .eq('id', userId)
      .single()
    if (error) throw error
    const maxAbsentDays = data.max_absent_days || 4
    const currentAbsentDays = data.current_absent_days || 0
    return {
      maxAbsentDays,
      currentAbsentDays,
      remainingDays: maxAbsentDays - currentAbsentDays,
      excessDays: Math.max(0, currentAbsentDays - maxAbsentDays)
    }
  } catch (error) {
    return {
      maxAbsentDays: 4,
      currentAbsentDays: 0,
      remainingDays: 4,
      excessDays: 0
    }
  }
}

export async function updateMaxAbsentDays(userId: string, days: number) {
  try {
    const { data, error } = await supabase
      .from('users')
      .update({ max_absent_days: days })
      .eq('id', userId)
      .select()
      .single()
    if (error) throw error
    return { data, error: null }
  } catch (error: any) {
    return { data: null, error }
  }
}

export async function getAbsentEmployeesToday(branchId?: string) {
  try {
    const today = new Date().toISOString().split('T')[0]
    
    // Get all attendances today
    const { data: attendances } = await supabase
      .from('attendance')
      .select('user_id')
      .eq('date', today)
      
    const presentUserIds = (attendances || []).map(a => a.user_id)
    
    // Get users not in presentUserIds
    let query = supabase.from('users').select('*').eq('status', 'active')
    if (branchId && branchId !== 'all') {
      query = query.eq('branch_id', branchId)
    }
    const { data: allActiveUsers } = await query
    
    const absentUsers = (allActiveUsers || []).filter(u => !presentUserIds.includes(u.id))
    return absentUsers
  } catch (error) {
    return []
  }
}

export async function getEmployeeStats(userId: string) {
  try {
    const { data: items } = await supabase
      .from('transaction_items')
      .select('unit_price, quantity, commission_amount')
      .eq('barber_id', userId)
      
    const totalTransactions = items?.length || 0
    let totalRevenue = 0
    let totalCommission = 0
    items?.forEach(item => {
      totalRevenue += (Number(item.unit_price) * Number(item.quantity)) || 0
      totalCommission += Number(item.commission_amount) || 0
    })
    
    const { data: points } = await supabase
      .from('points')
      .select('points_earned, points_type')
      .eq('user_id', userId)
      
    let bonusPoints = 0
    let penaltyPoints = 0
    points?.forEach(p => {
      if (p.points_earned > 0) bonusPoints += p.points_earned
      else penaltyPoints += Math.abs(p.points_earned)
    })
    
    return {
      totalTransactions,
      totalRevenue,
      totalCommission,
      averageTransaction: totalTransactions > 0 ? totalRevenue / totalTransactions : 0,
      bonusPoints,
      penaltyPoints,
      totalBonus: bonusPoints * 1000,
      totalPenalty: penaltyPoints * 1000
    }
  } catch (error) {
    return null
  }
}

export async function getEmployeeCommissions(userId: string) {
  try {
    const { data, error } = await supabase
      .from('commission_rules')
      .select('*')
      .eq('user_id', userId)
    if (error) throw error
    return { data: data || [], error: null }
  } catch (error: any) {
    return { data: [], error }
  }
}

export async function getEmployeeAttendance(userId: string) {
  try {
    const { data, error } = await supabase
      .from('attendance')
      .select('*')
      .eq('user_id', userId)
      .order('date', { ascending: false })
    if (error) throw error
    
    const presentDays = data?.filter(a => a.status === 'present').length || 0
    const lateDays = data?.filter(a => a.status === 'late').length || 0
    const totalDays = data?.length || 0
    const attendanceRate = totalDays > 0 ? ((presentDays + lateDays) / totalDays) * 100 : 100
    
    return { 
      data: data || [], 
      presentDays,
      lateDays,
      attendanceRate,
      overtimeHours: 0,
      error: null 
    }
  } catch (error: any) {
    return { data: [], error }
  }
}

export function setupEmployeeRealtime(callback: any) {
  return supabase
    .channel('users-changes')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'users' }, callback)
    .subscribe()
}

export async function addEmployee(data: any) {
  try {
    const insertData = {
      ...data,
      role: data.role || 'employee',
      // Provide a dummy password hash if not set. User can login with PIN or reset password later.
      password: data.password || '$2a$10$dummyHashDummyHashDummyHashDummyHashDummyHashDummyHa',
    }
    
    const { data: newEmp, error } = await supabase
      .from('users')
      .insert([insertData])
      .select()
      .single()
    if (error) throw error
    return { data: newEmp, error: null }
  } catch (error: any) {
    console.error('[addEmployee] Error:', error)
    return { data: null, error }
  }
}

export async function updateEmployee(id: string, data: any) {
  try {
    const { data: updatedEmp, error } = await supabase
      .from('users')
      .update(data)
      .eq('id', id)
      .select()
      .single()
    if (error) throw error
    return { data: updatedEmp, error: null }
  } catch (error: any) {
    console.error('[updateEmployee] Error:', error)
    return { data: null, error }
  }
}

export async function deleteEmployee(id: string) {
  try {
    const { error } = await supabase
      .from('users')
      .delete()
      .eq('id', id)
    if (error) throw error
    return { data: true, error: null }
  } catch (error: any) {
    console.error('[deleteEmployee] Error:', error)
    return { data: null, error }
  }
}

export async function getKasbonRequests(branchId?: string) {
  return getKasbon(branchId)
}

export async function createKasbonRequest(data: any) {
  try {
    console.log('[createKasbonRequest] Data yang dikirim:', JSON.stringify(data, null, 2))
    
    const { data: kasbon, error } = await supabase
      .from('kasbon')
      .insert({
        user_id: data.user_id,
        amount: data.amount,
        reason: data.reason,
        status: 'pending',
        request_date: new Date().toISOString(),
        due_date: data.due_date,
        notes: data.notes,
      })
      .select()
      .single()
    
    if (error) {
      console.error('[createKasbonRequest] Supabase error:', {
        message: error.message,
        details: error.details,
        hint: error.hint,
        code: error.code
      })
      throw error
    }
    
    console.log('[createKasbonRequest] Berhasil:', kasbon)
    return { data: kasbon, error: null }
  } catch (error: any) {
    console.error('[createKasbonRequest] Error:', {
      message: error?.message,
      name: error?.name,
      full: error
    })
    return { data: null, error }
  }
}

export function setupGlobalEventsListener(callback: any) {
  const channel = supabase
    .channel('global-events')
    .on('broadcast', { event: '*' }, (payload) => {
      callback(payload.event, payload.payload)
    })
    .subscribe()
  
  return channel
}

export async function getAllExpensesWithDetails() {
  try {
    const { data: expenses, error } = await supabase
      .from('expenses')
      .select(`
        *,
        branches:branch_id (
          id,
          name
        )
      `)
      .order('created_at', { ascending: false })
    
    if (error) throw error
    return { data: expenses || [], error: null }
  } catch (error: any) {
    console.error('[getAllExpensesWithDetails] Error:', error)
    return { data: [], error }
  }
}

export async function getExpenseStatisticsByBranch() {
  try {
    const { data: expenses, error } = await supabase
      .from('expenses')
      .select('*')
    
    if (error) throw error
    
    const stats = {
      total: expenses?.length || 0,
      pending: expenses?.filter(e => e.status === 'pending').length || 0,
      approved: expenses?.filter(e => e.status === 'approved').length || 0,
      rejected: expenses?.filter(e => e.status === 'rejected').length || 0,
      paid: expenses?.filter(e => e.status === 'paid').length || 0,
      totalAmount: expenses?.reduce((sum, e) => sum + (e.amount || 0), 0) || 0,
      pendingAmount: expenses?.filter(e => e.status === 'pending').reduce((sum, e) => sum + (e.amount || 0), 0) || 0,
      approvedAmount: expenses?.filter(e => e.status === 'approved').reduce((sum, e) => sum + (e.amount || 0), 0) || 0,
      rejectedAmount: expenses?.filter(e => e.status === 'rejected').reduce((sum, e) => sum + (e.amount || 0), 0) || 0,
      paidAmount: expenses?.filter(e => e.status === 'paid').reduce((sum, e) => sum + (e.amount || 0), 0) || 0,
    }
    
    return stats
  } catch (error: any) {
    console.error('[getExpenseStatisticsByBranch] Error:', error)
    return {
      total: 0,
      pending: 0,
      approved: 0,
      rejected: 0,
      paid: 0,
      totalAmount: 0,
      pendingAmount: 0,
      approvedAmount: 0,
      rejectedAmount: 0,
      paidAmount: 0,
    }
  }
}

export async function updateExpenseStatus(id: string, status: string, rejectionReason?: string) {
  try {
    const updateData: any = {
      status,
      updated_at: new Date().toISOString()
    }
    
    if (status === 'rejected' && rejectionReason) {
      updateData.rejection_reason = rejectionReason
    }
    
    if (status === 'approved') {
      updateData.approved_at = new Date().toISOString()
    }
    
    const { data, error } = await supabase
      .from('expenses')
      .update(updateData)
      .eq('id', id)
      .select()
      .single()
    
    if (error) throw error
    return { data, error: null }
  } catch (error: any) {
    console.error('[updateExpenseStatus] Error:', error)
    return { data: null, error }
  }
}

export function broadcastTransactionEvent(event: string, data: any) {
  const channel = supabase.channel('global-events')
  channel.send({
    type: 'broadcast',
    event: event,
    payload: data
  })
}

export async function deleteExpenseRequest(id: string) {
  try {
    const { error } = await supabase
      .from('expenses')
      .delete()
      .eq('id', id)
    
    if (error) throw error
    return { data: true, error: null }
  } catch (error: any) {
    console.error('[deleteExpenseRequest] Error:', error)
    return { data: false, error }
  }
}

export function setupTransactionsRealtime(callback: any) {
  return supabase
    .channel('transactions_changes')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'transactions' }, callback)
    .subscribe()
}

export function setupKomisiRealtime(callback: any) {
  return { unsubscribe: () => {} }
}

export async function getEmployeeAttendanceWithPhotos(userId: string, limit = 30) {
  try {
    const { data, error } = await supabase
      .from('attendance')
      .select('*')
      .eq('user_id', userId)
      .order('date', { ascending: false })
      .limit(limit)
    
    if (error) throw error
    return { data: data || [], error: null }
  } catch (error: any) {
    console.error('[getEmployeeAttendanceWithPhotos] Error:', error)
    return { data: [], error }
  }
}

export async function getEmployeePhotos(userId: string, limit = 20) {
  try {
    const { data, error } = await supabase
      .from('attendance')
      .select('*')
      .eq('user_id', userId)
      .or('check_in_photo.not.is.null,check_out_photo.not.is.null')
      .order('date', { ascending: false })
      .limit(limit)
    
    if (error) throw error
    return { data: data || [], error: null }
  } catch (error: any) {
    console.error('[getEmployeePhotos] Error:', error)
    return { data: [], error }
  }
}

export async function getApprovedExpenses(branchId?: string) {
  return getExpenses(branchId, 'approved')
}

export async function getExpenseStatistics(branchId?: string) {
  return { data: null, error: null }
}

export async function createExpenseRequest(data: any) {
  try {
    console.log('[createExpenseRequest] Data yang dikirim:', JSON.stringify(data, null, 2))
    
    // Get current user from localStorage as fallback
    let requestedBy = data.requested_by
    if (!requestedBy && typeof window !== 'undefined') {
      const userStr = localStorage.getItem('user')
      if (userStr) {
        const user = JSON.parse(userStr)
        requestedBy = user.id
      }
    }
    
    const { data: expense, error } = await supabase
      .from('expenses')
      .insert({
        branch_id: data.branch_id,
        category: data.category,
        description: data.description,
        amount: data.amount,
        status: 'pending',
        notes: data.notes,
        requested_by: requestedBy,
        expense_date: new Date().toISOString(), // Add expense_date
      })
      .select()
      .single()
    
    if (error) {
      console.error('[createExpenseRequest] Supabase error:', {
        message: error.message,
        details: error.details,
        hint: error.hint,
        code: error.code
      })
      throw error
    }
    
    console.log('[createExpenseRequest] Berhasil:', expense)
    return { data: expense, error: null }
  } catch (error: any) {
    console.error('[createExpenseRequest] Error:', {
      message: error?.message,
      name: error?.name,
      full: error
    })
    return { data: null, error }
  }
}

export async function updateExpenseRequest(id: string, data: any) {
  try {
    const { data: expense, error } = await supabase
      .from('expenses')
      .update(data)
      .eq('id', id)
      .select()
      .single()
    
    if (error) throw error
    return { data: expense, error: null }
  } catch (error: any) {
    console.error('[updateExpenseRequest] Error:', error)
    return { data: null, error }
  }
}

export async function getUsersWithPoints(branchId?: string) {
  try {
    let query = supabase
      .from('users')
      .select(`
        id,
        name,
        email,
        position,
        branch_id,
        status
      `)
      .eq('status', 'active')
    
    // Filter by branch if specified and not "all"
    if (branchId && branchId !== 'all') {
      query = query.eq('branch_id', branchId)
    }
    
    const { data: users, error: usersError } = await query
    if (usersError) throw usersError
    
    // Get branch names separately
    const { data: branches } = await supabase
      .from('branches')
      .select('id, name')
    
    const branchMap = new Map(branches?.map(b => [b.id, b]) || [])
    
    // Get points for each user
    const usersWithPoints = await Promise.all(
      (users || []).map(async (user) => {
        // Get total points
        const { data: pointsData } = await supabase
          .from('points')
          .select('points_earned')
          .eq('user_id', user.id)
        
        const totalPoints = pointsData?.reduce((sum, p) => sum + (p.points_earned || 0), 0) || 0
        
        // Get monthly points (current month)
        const startOfMonth = new Date()
        startOfMonth.setDate(1)
        startOfMonth.setHours(0, 0, 0, 0)
        
        const { data: monthlyData } = await supabase
          .from('points')
          .select('points_earned')
          .eq('user_id', user.id)
          .gte('created_at', startOfMonth.toISOString())
        
        const monthlyPoints = monthlyData?.reduce((sum, p) => sum + (p.points_earned || 0), 0) || 0
        
        return {
          ...user,
          branches: user.branch_id ? branchMap.get(user.branch_id) : null,
          total_points: totalPoints,
          monthly_points: monthlyPoints,
          rank: 0 // Will be calculated after sorting
        }
      })
    )
    
    // Sort by total points and assign ranks
    const sorted = usersWithPoints.sort((a, b) => (b.total_points || 0) - (a.total_points || 0))
    sorted.forEach((user, index) => {
      user.rank = index + 1
    })
    
    return { data: sorted, error: null }
  } catch (error: any) {
    console.error('[getUsersWithPoints] Error:', error)
    return { data: [], error }
  }
}

export async function getPointsStatistics(branchId?: string) {
  try {
    const { data: users, error } = await getUsersWithPoints(branchId)
    if (error) throw error
    
    const totalEmployees = users.length
    const topPerformer = users[0] || null
    const totalPoints = users.reduce((sum, u) => sum + (u.total_points || 0), 0)
    const averagePoints = totalEmployees > 0 ? Math.round(totalPoints / totalEmployees) : 0
    
    return {
      data: {
        totalEmployees,
        topPerformer,
        averagePoints,
        totalPoints
      },
      error: null
    }
  } catch (error: any) {
    console.error('[getPointsStatistics] Error:', error)
    return {
      data: {
        totalEmployees: 0,
        topPerformer: null,
        averagePoints: 0,
        totalPoints: 0
      },
      error
    }
  }
}

export async function getPointTransactions(branchId?: string) {
  try {
    // Get all points
    const { data: points, error: pointsError } = await supabase
      .from('points')
      .select('*')
      .order('created_at', { ascending: false })
    
    if (pointsError) throw pointsError
    
    // Get all users
    const { data: users } = await supabase
      .from('users')
      .select('id, name, branch_id')
    
    // Get all branches
    const { data: branches } = await supabase
      .from('branches')
      .select('id, name')
    
    // Create maps for quick lookup
    const userMap = new Map(users?.map(u => [u.id, u]) || [])
    const branchMap = new Map(branches?.map(b => [b.id, b]) || [])
    
    // Combine data
    const transactions = (points || []).map(point => {
      const user = userMap.get(point.user_id)
      const branch = user?.branch_id ? branchMap.get(user.branch_id) : null
      
      return {
        ...point,
        users: user ? {
          id: user.id,
          name: user.name,
          branch_id: user.branch_id,
          branches: branch
        } : null
      }
    })
    
    // Filter by branch if specified and not "all"
    const filtered = (branchId && branchId !== 'all')
      ? transactions.filter(t => t.users?.branch_id === branchId)
      : transactions
    
    return { data: filtered, error: null }
  } catch (error: any) {
    console.error('[getPointTransactions] Error:', error)
    return { data: [], error }
  }
}

export async function reduceOutletStock(serviceId: string, quantity: number) {
  return { data: null, error: null }
}

export function subscribeToEvents(callback: any) {
  return { unsubscribe: () => {} }
}
